#!/bin/bash

if [[ $(id -u) -ne 0 ]] ; then
    echo "Please run as root"
    exit 1
fi

conffile=/etc/courier/imapd-ssl

if [ ! -f $conffile ]
then
    echo "$conffile not found, install courier-imap"
    exit 1
fi

./usr/local/bin/letsimap

if [ $? -eq 0 ]
then
    groupadd letsencrypt
    usermod -a -G letsencrypt courier
    chgrp letsencrypt /etc/letsencrypt/live
    chmod g+rx /etc/letsencrypt/live
    cp usr/local/bin/* /usr/local/bin/
    cp etc/cron.d/* /etc/cron.d/
fi
